- name: Get openhim-console relase
  get_url: dest=/tmp/openhim-console.tar.gz
           url={{openhim_console_url}}
           
- name: Extract archive to web root
  unarchive: copy=no
             dest={{openhim_console_web_root}}
             src=/tmp/openhim-console.tar.gz

- name: Insert config file
  template: src=default.json.j2
            dest={{openhim_console_web_root}}/config/default.json

