- name: Get openhim-console relase
  get_url: dest=/tmp/openhim-console.tar.gz
           url=https://github.com/jembi/openhim-console/releases/download/{{openhim_console_version}}/openhim-console.tar-{{openhim_console_version}}.gz
           
- name: Extract archive to web root
  unarchive: copy=no
             dest={{openhim_console_web_root}}
             src=/tmp/openhim-console.tar.gz

- name: Insert config file
  template: src=default.json.j2
            dest={{openhim_console_web_root}}/config/default.json

