---
- name: Install webserver
  apt: name=nginx
       state=installed

- include: deploy.yml
  when: openhim_console_deploy

- include: install.yml
  when: not openhim_console_deploy and openhim_console_branch is undefined

- include: git.yml
  when: not openhim_console_deploy and openhim_console_branch is defined

- name: ensure web server is started
  service: name=nginx
           state=started
           enabled=yes
