---
- name: Install webserver
  apt: name={{openhim_webserver}}
       state=installed

- include: deploy.yml
  when: openhim_console_deploy

- include: install.yml
  when: not openhim_console_deploy

- name: ensure web server is started
  service: name={{openhim_webserver}}
           state=started
           enabled=yes
